HTML & CSS 課題1
sanuki0679/css_exercise pull request #1
Opened 2023-03-11 06:34 UTC by sanuki0679

HTML & CSS 課題1 が完了したので提出します。確認おねがいします。

2023-03-11 07:47 UTC, naoto1192 requested changes
いくつか修正お願いします😊

<img width="1392" alt="スクリーンショット_2023-03-11_16_40_26" src="https://user-images.githubusercontent.com/98454350/224472169-42d4f5dd-aff5-4d3b-92ba-66aea9107acb.png">

2023-03-11 07:47 UTC, naoto1192 commented on css/style.css
> +}
`ul`と`sns-list`はひとつにまとめられそうですね😌

2023-03-11 07:47 UTC, naoto1192 commented on css/style.css
> +    text-transform: uppercase;
`text-transform: uppercase;`は必要ないかなと思いますので、削除でお願いします🙏

2023-03-12 01:10 UTC, zeeero4 commented on css/style.css
> +
そのそも　ul タグに sns-listというクラス名を指定しているので、
以下で問題ないかと思います！

```
.sns-list {
    display: flex;
    font-size: 2rem;
    margin-top: 34px;
    list-style: none;
}
```

2023-03-12 02:25 UTC, merged